dist: xenial

language: generic

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - maven

cache:
  directories:
    - $HOME/.m2

install: true

before_script:
  - pip install --user codecov
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-${TRAVIS_CPU_ARCH}"
  - echo $JAVA_HOME
  - export MAVEN_OPTS="-Djava.home=$JAVA_HOME"
  - export PATH=$JAVA_HOME/bin:$PATH

script:
  - mvn -U -B -V test --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

after_success:
  - mvn clean test jacoco:report
  - codecov --build "$TRAVIS_JOB_NUMBER-jdk8"

notifications:
  email:
    on_failure: change
