dist: xenial

language: java

jdk: openjdk8

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - maven

cache:
  directories:
    - $HOME/.m2

install: true

before_script:
  - pip install --user codecov
  - JAVA_REAL_PATH=$(realpath /usr/bin/java)
  - echo "REAL: $JAVA_REAL_PATH"
  - export JAVA_HOME=$(dirname $(dirname $(dirname $JAVA_REAL_PATH)))
  - echo $JAVA_HOME
  - export PATH=$JAVA_HOME/bin:$PATH

script:
  - mvn -U -B -V test --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

after_success:
  - mvn clean test jacoco:report
  - codecov --build "$TRAVIS_JOB_NUMBER-jdk8"

notifications:
  email:
    on_failure: change
